// app/layout.tsx
import type { Metadata } from "next";
import "../globals.css"; // مسیر این فایل را بر اساس پوشه‌بندی خود چک کنید

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <div>HeaderUser</div>

        <main className="w-full mx-auto container flex-grow">{children}</main>

        <div>FooterUser</div>
      </body>
    </html>
  );
}
