
import AdminHeader from "@/src/components/admin/AdminHeader";
import AdminSidebar from "@/src/components/admin/AdminSidebar";



// import "../globals.css";

// export const metadata: Metadata = {
//   title: "Sportex",
//   description: "Generated by create next app",
// };

// export default function AdminLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html >
//       <body className="min-h-full flex flex-col">
//         <div>HeaderAdmin</div>
//         <div className="w-full mx-auto container">{children}</div>

//         <div>FooterAdmin</div>
//       </body>
//     </html>
//   );
// }

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen bg-gray-50" dir="rtl">
      {/* سایدبار سمت راست */}
      <AdminSidebar />

      {/* بخش اصلی شامل هدر و محتوا */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <AdminHeader />
        <main className="flex-1 overflow-x-hidden overflow-y-auto p-6">
          {children}
        </main>
      </div>
    </div>
  );
}
