import type { Metadata } from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <div>HeaderAdmin</div>
        <div className="w-full mx-auto container">{children}</div>

        <div>FooterAdmin</div>
      </body>
    </html>
  );
}
